### ISSUE TITLE
怎么测试这工程呢 (How to inference the model)

### ISSUE THREAD

**Issue by sssssshf** [MCG-NJU/MOTIP#1]
测试代码什么时候发布 啊 训练

**Comment by HELLORPG** [comment]
目前正在整理注释和删除冗余代码，正在逐步上传代码。
拟先上传推理部分的代码，训练的代码可能会稍微晚一两周，因为整理起来需要一点时间，同时还有其他工作在推进。
届时会在 [README: News :fire:](https://github.com/MCG-NJU/MOTIP?tab=readme-ov-file#news-fire) 中更新进度，我到时候也会在这个 Issue 中提醒您。

**Comment by HELLORPG** [comment]
推理代码和模型参数预计会在明后天发布 :soon:。感谢理解～

**Comment by sssssshf** [comment]
> 推理代码和模型参数预计会在明后天发布 🔜。感谢理解～
感谢大佬回复，目前正在拜读论文，有一些疑问整理后还请帮忙解答疑惑

**Comment by HELLORPG** [comment]
现在推理代码已经可用了，具体使用方式参考[这里](https://github.com/MCG-NJU/MOTIP?tab=readme-ov-file#quick-start-dash).

---------------------

The evaluation code is available now. Following the instructions [here](https://github.com/MCG-NJU/MOTIP?tab=readme-ov-file#quick-start-dash).
