### ISSUE TITLE
batch_size可以设置多少

### ISSUE THREAD

**Issue by zxhasd** [MCG-NJU/MOTIP#11]
感谢您的分享，请问您的代码batch_size可以设置多少，是像MOTR一样只能设置为1吗

**Comment by HELLORPG** [comment]
您好，很高兴您关注到我们的工作。

目前来说，我们的代码仅支持 batch_size = 1：
https://github.com/MCG-NJU/MOTIP/blob/742d25a4ca6e0eb77e07334f43d95959d70496af/models/seq_decoder.py#L167
因为 trajectory history 是不等长的，如果要支持 batch_size > 1 的话会有些麻烦（需要对齐长度并且增加 mask）。但是我后续会持续完善这个仓库，应该会增加 BS > 1 的代码支持。

但是短期之内，这个需求应该不是很强烈，因为现在 BS=1 的情况下，已经需要 24GB 及以上的显存进行训练了，除非你的机器显存大于 48GB，不然的话更大的 BS 并不具备太强的可行性。

**Comment by zsz00** [comment]
希望您写个详细解读这个论文的文章, 因为这个方法跟之前的motr 系列有很多不同, 需要跟多的理解和对比. 那对学习这个论文有很大帮助.

**Comment by HELLORPG** [comment]
感谢关注。应该会考虑出一篇中文解读的文章的。但是由于这些事情都是我一个人在做，同期还有其他的工作需要推进，因此可能具体时间上还不能保证。
