### ISSUE TITLE
您好请问能提供下seqs map文件吗（The `val_seqmap.txt` file of SportsMOT dataset）

### ISSUE THREAD

**Issue by hanzifan** [MCG-NJU/MOTIP#13]
如题，我在sportsmot的数据集里没有发现seqmap文件，但是我看您的val代码需要seqmap，请问能否提供一下。

**Comment by HELLORPG** [comment]
这个文件是一个视频序列的文本列表，可以参考 DanceTrack 的自己生成，如果你着急的话。
或者等我吃完饭之后，我从服务器下载一下然后传过来。

**Comment by hanzifan** [comment]
> 这个文件是一个视频序列的文本列表，可以参考 DanceTrack 的自己生成，如果你着急的话。 或者等我吃完饭之后，我从服务器下载一下然后传过来。

ok了解了

**Comment by hanzifan** [comment]
> [val_seqmap.txt](https://github.com/MCG-NJU/MOTIP/files/15329856/val_seqmap.txt)

感谢
