### ISSUE TITLE
30秒的一个视频花了2分多钟，这个正常吗

### ISSUE THREAD

**Issue by tppqt** [MCG-NJU/MOTIP#14]
3060的显卡
![01af0246d7d68d11990c613257ecea8](https://github.com/MCG-NJU/MOTIP/assets/19279148/2ddfcf22-97e1-4570-bfe3-23c1993183ae)

**Comment by tppqt** [comment]
127/750=0.17，相当于6FPS，没有达到16FPS啊

**Comment by HELLORPG** [comment]
我们 Supp B.3 中，FPS 是在 4090 上使用 FP32 精度进行推理得到的结果。
3060 的算力大概和 TiTAN XP 同级别，按照我们之前的经验的话，差不多就是 6～7.5 这个 FPS 范围，具体波动可能取决于：
1. CPU 资源。
2. 内存频率。
3. 硬盘读取速度（一般取决于是否是 SSD）。

我手边没有 3060，所以目前没有办法复现你的条件。
之后有资源的时候我可以测试一下在 TiTAN XP 上的速度。

**Comment by HELLORPG** [comment]
在我们 TiTAN XP 机器上的结果是：
<img width="1401" alt="image" src="https://github.com/MCG-NJU/MOTIP/assets/41836383/bdca7e09-d00c-4562-953b-5c51fa7e3e33">

**Comment by tppqt** [comment]
这个速度还是有点慢哈，你们之前那个基于sportsMOT进行多目标跟踪的有没有速度快一点的啊

**Comment by HELLORPG** [comment]
这个速度是由 Deformable DETR 的固有速度决定的，目前没有更快的结果。
可以通过 FP16 等类似的技术进行加速，提速大概有 50% 左右。
