### ISSUE TITLE
Inconsistency in the number of iterations for MOT17

### ISSUE THREAD

**Issue by GianlucaMancusi** [MCG-NJU/MOTIP#21]
Hi, I am using the configuration file [r50_deformable_detr_motip_mot17.yaml](https://github.com/MCG-NJU/MOTIP/blob/main/configs/r50_deformable_detr_motip_mot17.yaml) to reproduce the MOT17 numbers.
However, I noticed in your MOT17 training [logs](https://drive.google.com/file/d/1RB0XasyMMJFziB5wuyT208jMBLW37CPM/view) that the number of iterations with eight GPUs is 3717 per epoch.
For me, with the same number of GPUs, I have 6309 iterations per epoch.

Instead, with the DanceTrack configuration files [r50_deformable_detr_motip_dancetrack.yaml](https://github.com/MCG-NJU/MOTIP/blob/main/configs/r50_deformable_detr_motip_dancetrack.yaml), [r50_deformable_detr_motip_dancetrack_trainval_joint_ch.yaml](https://github.com/MCG-NJU/MOTIP/blob/main/configs/r50_deformable_detr_motip_dancetrack_trainval_joint_ch.yaml) the number of iterations for each epoch is the same in my case and your [log1](https://drive.google.com/file/d/1XRRBjw92bQk7FUGxmZSsrTf5BjXbL2pp/view) file (5030) and [log2](https://drive.google.com/file/d/112n-ziOG8qfvyH8WK8x2Sqa7BPfIDTr7/view) file (10518). So DanceTrack and CrowdHuman are ok.

Can you rerun the MOT17 experiment to see if the number of iterations is correct for such a configuration file?

**Comment by HELLORPG** [comment]
I guess the problem is caused by data preparation.
As I mentioned [here](https://github.com/MCG-NJU/MOTIP/blob/main/docs/DATASET.md#file-tree), I delete some duplicated videos in MOT17:
> ⚠️ Since each video sequence in MOT17 is stored three times, for each training video sequence, you should delete the other two sequences to achieve deduplication. For instance, in my experiment, I only retained the ‘xxx-DPM’ sequences.”

I'm sorry that it is unusual, and I'll make it better in the future. However, I think this will take some time, cause I'm so busy these days. I'm considering hiring a clone just to keep up!! 😄
