### ISSUE TITLE
advice about code, which may cause problems while developing on python3.8

### ISSUE THREAD

**Issue by lzr-qifei** [MCG-NJU/MOTIP#22]
Hi, thank you for your wonderful work!
I notice that you use 
`    def save_metrics(self, metrics: Metrics, prompt: str = "",
                     fmt: None | str = "{average:.4f} ({global_average:.4f})",
                     statistic: None | str = "average", global_step: int = 0, prefix: None | str = None,
                     x_axis_step: None | int = None, x_axis_name: None | str = None,
                     filename: str = "log.txt", file_mode: str = "a"):`
this would cause problems while developing on python3.8：
`TypeError: unsupported operand type(s) for |: 'NoneType' and 'type'`，
according to https://stackoverflow.com/questions/69440494/python-3-10-optionaltype-or-type-none, this code is unfriendly to those using python lower than 3.10.
Would you fix it? or give me some advice to develop it on python3.8

**Comment by lzr-qifei** [comment]
Besides, I am using single GPU, is this project suitable to train on single 4090?

**Comment by lzr-qifei** [comment]
Already solved, I turn 
`fmt: None | str = "{average:.4f} ({global_average:.4f})",` into 
`fmt:Optional[str] = "{average:.4f} ({global_average:.4f})",`.
This format would be run on both python 3.10 and versions lower, so that makes your code more robust.

**Comment by HELLORPG** [comment]
> Besides, I am using single GPU, is this project suitable to train on single 4090?

Only using one GPU may bring different convergence results because the Batch Size is reduced.
One possible idea is to set `ACCUMULATE_STEPS` to `16`, but this does not guarantee the same performance. In my experience, this may result in some performance degradation.
