### ISSUE TITLE
Pre-training scripts

### ISSUE THREAD

**Issue by GianlucaMancusi** [MCG-NJU/MOTIP#23]
Hi, when will the detection pre-training be released? Thank you for your time and assistance.
I need the pre-training scripts to pretrain on another pedestrian dataset (MOTSynth and maybe PersonPath22). 
In the meantime, is it a good idea to start the training from the MOT17 detection-pretraining? Would you happen to have any suggestions on this? 
Thank you!

**Comment by HELLORPG** [comment]
I will try my best to upload the pre-train configuration file within this week. 
I guess the pre-training of MOT17 is not very important, because its diversity is far less than the two datasets you mentioned and CrowdHuman. You may consider combining CrowdHuman for per-training.

BTW, I've seen the issue you created in the repo of PersonPath22. Have you gotten the full-FPS annotations yet? I also tried to experiment on this but got stuck here. 
Another BTW, is everything well when reproducing on MOT17? Currently, I don't have enough resources to reproduce this experiment. So your feedback is very important to me.

**Comment by GianlucaMancusi** [comment]
> I will try my best to upload the pre-train configuration file within this week.

Thank you!

> BTW, I've seen the issue you created in the repo of PersonPath22. Have you gotten the full-FPS annotations yet? I also tried to experiment on this but got stuck here.

Yes, I tried to interpolate. I can not guarantee that the script is correct. This is the [script](https://gist.github.com/GianlucaMancusi/b396d25fdac4c7f29ae8190bcd267e3f) to convert from PersonPath22 to MOTChallenge format together with the interpolation script. Let me know if it sounds good to you. We can work on it. Please feel free to comment on it if you find any issues.

> Another BTW, is everything well when reproducing on MOT17? Currently, I don't have enough resources to reproduce this experiment. So your feedback is very important to me.

I am still training it. I will let you know.
Instead for DanceTrack I had slightly lower results:
|       | HOTA | DetA | AssA | MOTA | IDF1 |
|-------|------|------|------|------|------|
| MOTIP | **67.5** | **79.4** | **57.6** | **90.3** | **72.2** |
| REPRODUCED | 66.9 | 79.1 | 56.8 | 89.7 | 71.4 |

**Comment by HELLORPG** [comment]
I have uploaded the pre-training configuration files on DanceTrack and SportsMOT as references. The configs on MOT17 are more complicated, so I need to check them later. 

> Yes, I tried to interpolate. I can not guarantee that the script is correct. This is the [script](https://gist.github.com/GianlucaMancusi/b396d25fdac4c7f29ae8190bcd267e3f) to convert from PersonPath22 to MOTChallenge format together with the interpolation script. Let me know if it sounds good to you. We can work on it. Please feel free to comment on it if you find any issues.

Thank you so much for your script. I'll try it out later and will contact you if I have any questions.

> Do you think this is a reasonable fluctuation, or should it result in the same? Trained on 8 A100 with two interruptions.

Yes, I think it's a reasonable fluctuation, as I discussed [here](https://github.com/MCG-NJU/MOTIP/blob/main/docs/GET_STARTED.md#default-scripts). This is quite frustrating, but I've found that almost all E2E MOT methods have this problem. I'll try to address that in the future as well, but I feel like this seems to be a purely training technique issue.

**Comment by HELLORPG** [comment]
I have uploaded the configuration files and scripts required for pre-training. If there are any issues, please feel free to contact me.
