### ISSUE TITLE
关于推理速度

### ISSUE THREAD

**Issue by shirosy** [MCG-NJU/MOTIP#3]
今天才发现大佬发了新作，ID decoder的想法非常novel。我想问问推理速度的问题，在detr的上面堆叠额外6层decoder layer，而且是串行计算，应该会慢很多吧，可是论文却表示和MOTR帧率相当（16帧），这是为什么呢。

**Comment by HELLORPG** [comment]
感谢您关注到我们的工作。
我们的 DETR 在推理阶段，其实只需要每一帧做一次，然后将 query 的输出结果存下来就可以了（成本可以忽略不计），因此这部分和 MOTR 的开销是一样的。
不一样的部分在于，MOTR 额外需要运算一个 query updating，而我们需要额外计算一个 ID Decoder。ID Decoder 中主要的计算量就来自于 FFN 和 Cross-Attention，这两部分的计算量和 DETR 相比，完全是九牛一毛。也正因如此，其实我们的方法的主要计算开销还是来自每帧一次的 DETR，所以也具有和 MOTR 相近的推理速度。
此外，你提到的串行计算，在我的理解里面应该只有 DETR 和 ID Decoder 是串行的，如前面分析的，ID Decoder 并不会产生太大的计算量差距。**因此，其实我们的速度主要由每一帧一次的 DETR 计算量所决定。**

**Comment by shirosy** [comment]
哦哦，是我没有仔细考虑ID Decoder的query数量，确实要少很多。我明白了，谢谢您。

**Comment by HELLORPG** [comment]
不用谢～
那我就暂时关闭这一 issue 了，如果有需要您可以再次打开。
