### ISSUE TITLE
How much RAM is needed for training?

### ISSUE THREAD

**Issue by bkkm78** [MCG-NJU/MOTIP#31]
I tried training on DanceTrack following `r50_deformable_detr_motip_dancetrack.yaml` on a 4-GPU workstation. The workstation's 128 GB RAM was quickly filled up, which was likely the cause that the training script failed quickly after logging the first loss messaeg. Do we have a record of how much RAM is needed for training (host RAM, not GPU memory)?

**Comment by HELLORPG** [comment]
I don't have any spare GPU servers at this moment. 
However, I tried the single-GPU training on my personal machine, which has 32 GB RAM. It also filled up quickly (and failed), as you mentioned. It seems that a single GPU requires more than 32 GB RAM.
One possible solution is to reduce `num_workers`. I set it to `4`, and it seems everything is OK.

**Comment by bkkm78** [comment]
Thanks. Reducing `num_workers` works.

**Comment by HELLORPG** [comment]
Improving the code for data loading may reduce RAM allocation. 

BTW, I will release a new version in early December that should reduce the CPU and RAM usage when loading data. I will quote this issue to remind you when the time comes.

**Comment by bkkm78** [comment]
That would be wonderful! Thank you very much.
