### ISSUE TITLE
Pytorch and CUDA version

### ISSUE THREAD

**Issue by FadhilRa** [MCG-NJU/MOTIP#34]
What is the right version of pytorch and cuda for this project? Because I have tried several versions of cuda always error

**Comment by HELLORPG** [comment]
You can refer to [our doc](https://github.com/MCG-NJU/MOTIP/blob/main/docs/INSTALL.md) to find more details.

**Comment by HELLORPG** [comment]
Since I haven't received a response for a while, I'll close this issue for a while. Feel free to re-open it if needed.
