### ISSUE TITLE
Threshold on model?

### ISSUE THREAD

**Issue by TheMattBin** [MCG-NJU/MOTIP#38]
Thanks for the great repo! I tried the model with my own video, but the tracking results might not be satisfactory as I expected. If I'm correct, the model should be E2E with DETR as backbone. I would like to know if I can set something like threshold to filter out or limit the cases of false positive during inference.

#### Env setup
OS: Linux
Python: 3.11
Cuda: 12.4

**Comment by HELLORPG** [comment]
Of course, we DO provide some threshold settings in our configuration files, as follow:
https://github.com/MCG-NJU/MOTIP/blob/1dda4c49b4e5df1bac6de2827d7ca780b48d8853/configs/r50_deformable_detr_motip_dancetrack.yaml#L110-L113
For the corresponding meaning and futher customization, please refer to following function:
https://github.com/MCG-NJU/MOTIP/blob/1dda4c49b4e5df1bac6de2827d7ca780b48d8853/submit_engine.py#L114-L122

**Comment by TheMattBin** [comment]
Thanks for the prompt response! That helps a lot!
