### ISSUE TITLE
训练代码有具体的公布日期吗?

### ISSUE THREAD

**Issue by WesLee88524** [MCG-NJU/MOTIP#5]
你好,这个工作非常棒! 
请问训练代码和MOT17预训练模型有具体公布日期吗?

**Comment by HELLORPG** [comment]
感谢您关注我们的工作～
MOT17 上的模型在节后就可以公开。
训练代码的话可能需要整理和精简一下，目前预计的话可能会需要两三周的时间。因为该工作还在审稿过程中，并且同期我还有其他工作需要推进一下，所以效率可能会稍微低一点😂

**Comment by HELLORPG** [comment]
我今天上传了 MOT17 上的模型、配置和日志，在[这里](https://github.com/MCG-NJU/MOTIP/commit/4efa26c71a9a8894688f49616dc8e3322f1e782e)。

但是这之中现在有可能（虽然可能性应该不大）存在错误，因为本来我应该重新再验证一次指标是否正确（在开源工作中，我们更新&重构了相当一部分的代码），但是现在评测的网站 [MOTChallenge](https://motchallenge.net/) 提交结果文件之后迟迟不给我返回评测结果，已经这样持续三天了。我目前在尝试发邮件联系管理人员。

**Comment by WesLee88524** [comment]
> 我今天上传了 MOT17 上的模型和日志，在[这里](https://drive.google.com/drive/folders/1sv6iXuHQxB5vkm4HNLQpvLqtrRUzSvDW?usp=drive_link)，并且在仓库中更新了配置文件。
> 
> 但是这之中现在有可能（虽然可能性应该不大）存在错误，因为本来我应该重新再验证一次指标是否正确（在开源工作中，我们更新&重构了相当一部分的代码），但是现在评测的网站 [MOTChallenge](https://motchallenge.net/) 提交结果文件之后迟迟不给我返回评测结果，已经这样持续三天了。我目前在尝试发邮件联系管理人员。

感谢!!!
我上传到MOTchallege的结果也没返回,hmmmm....😂

**Comment by HELLORPG** [comment]
我发邮件给他们到现在也没有人回复，感觉有点G，遥遥无期😂

**Comment by chongweiliu** [comment]
> 我发邮件给他们到现在也没有人回复，感觉有点G，遥遥无期😂

要是MOTChallenge从此真寄那MOT就要开启新时代了😂，顺带一提，BDD 服务器去年也寄了，不知道现在修好了吗。

**Comment by HELLORPG** [comment]
可不要乱说，哈哈哈，MOTChallenge 的维护者已经给我回邮件了，他说现在已经重新上线了。

BDD100K 的话，当初我们几个人讨论的 issue 和 discussion 中还没有人给我们说已经恢复了，感觉是还没有修好的样子，过段时间再试一下。

**Comment by chongweiliu** [comment]
> 可不要乱说，哈哈哈，MOTChallenge 的维护者已经给我回邮件了，他说现在已经重新上线了。
> 
> BDD100K 的话，当初我们几个人讨论的 issue 和 discussion 中还没有人给我们说已经恢复了，感觉是还没有修好的样子，过段时间再试一下。

MOTChallenge恢复就又能愉快的做科研了；希望BDD100K能尽早打赢复活赛。

**Comment by HELLORPG** [comment]
@WesLee88524 MOTChallenge 已经恢复了，但是需要注意，之前提交过结果的 Entry 会因为阻塞而无法使用（这个网站一直都有这个问题），所以需要新建一个 Entry 来提交。至少在我这边是的。
